xaynetwork/xayn_discovery_engine

.github/workflows/labeler.yml

Changing the configuration of the labeler CI to label when the base is any branch.

DEVOPS-672 Configuring labeler CI for any base

---

.github/workflows/release.yml
discovery_engine_flutter/pubspec.yaml

With the current release workflow the flutter plugin always depends on the `main` branch.
This PR change that to the previous commit so that it always depends on the same branch and at a fixed location.

TY 2295 Fix release ci

---

discovery_engine_core/core/src/document.rs

Ticket:
- [TY-2331](https://xainag.atlassian.net/browse/TY-2331)
- part of [TY-2282](https://xainag.atlassian.net/browse/TY-2282)
Summary:
Adds a snippet field to the `UserReacted` struct. The snippet field will be used by the kpe within the ranker.

TY-2331 add snippet field

---

discovery_engine_core/Cargo.lock
discovery_engine_core/core/Cargo.toml
discovery_engine_core/core/src/engine.rs
discovery_engine_core/core/src/stack/ops.rs
discovery_engine_flutter/example/pubspec.lock
discovery_engine_flutter/example/pubspec.yaml

**References**
- [TY-2301]
- [TY-2312]
- [TY-2313]
**Summary**
- async'ed the `stack::ops::Ops` trait and its `new_items()` function
- async'ed the `Engine::get_feed_documents()` method
- fixed dart linter warning
[TY-2301]: https://xainag.atlassian.net/browse/TY-2301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TY-2312]: https://xainag.atlassian.net/browse/TY-2312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TY-2313]: https://xainag.atlassian.net/browse/TY-2313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TY-2301 async engine

---

discovery_engine/lib/src/domain/feed_manager.dart
discovery_engine/lib/src/domain/models/document.dart

**Summary**
Previously,
- feed manager was added in #53 handling _docs closed_ and _next batch_.
- time stamps were added to documents in #64.
this pr adds handling of _restore feed_ to the feed manager.
the returned feed is ordered by `timestamp`, then `personalizedRank`.

TY-2267 feed manager: restore feed

---

web-api/src/app.rs
web-api/src/app/state.rs
web-api/src/ingestion.rs
web-api/src/ingestion/routes.rs
web-api/src/net.rs
web-api/tests/silo_management_api.rs

Do not run tenant/app specific middleware for the silo management endpoint.
Mainly do not require the `X-Xayn-Tenant-Id` header.
- [ET-4591]
[ET-4591]: https://xainag.atlassian.net/browse/ET-4591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ET-4591 no tenant middleware for silo management

---

.spectral.js
web-api/openapi/back_office.yaml
web-api/src/ingestion/routes.rs
web-api/tests/document_candidates.rs
web-api/tests/health.rs

**Reference**
- [ET-4628]
**Summary**
- move candidates endpoint to `/documents/_candidates`
- remove spec for deprecated endpoints to avoid visibility for new customers
- add deprecation header to the response for deprecated endpoints
[ET-4628]: https://xainag.atlassian.net/browse/ET-4628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ET-4628 move candidates endpoint

---

web-api/src/error/common.rs
web-api/src/personalization/routes.rs

**Reference**
- [ET-4634]
**Summary**
- don't clip the document count in front office requests silently, but return a bad request instead
[ET-4634]: https://xainag.atlassian.net/browse/ET-4634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ET-4634 don't clip document count silently

---

web-api-db-ctrl/elasticsearch/mapping.json

This PR does two things:
- set `dynamic` to `strict` for the outer most object as it allows us to find bugs in our code 
- add a definition for `tags` to the `mapping` 
- ~set `dynamic` to `runtime` for property fields so that they can be indexed in the future, this is fixing problems with a new filter by properties functionality~
**References:** 
- [ET-4630]
[ET-4630]: https://xainag.atlassian.net/browse/ET-4630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ET-4630-fix-dynamic-setting

---

web-api/openapi/front_office.yaml
web-api/src/mind/state.rs
web-api/src/personalization/knn.rs
web-api/src/personalization/routes.rs
web-api/src/storage.rs
web-api/src/storage/memory.rs
web-api/src/storage/postgres.rs
web-api/tests/personalized_documents.rs
web-api/tests/personalized_semantic_search.rs
web-api/tests/semantic_search.rs

**Reference**
- [ET-4632]
**Summary**
- only include document properties in the fronoffice responses if they are requested via the `include_properties` flag
- default the flag to `true` for now, it will be changed to false after some time
[ET-4632]: https://xainag.atlassian.net/browse/ET-4632?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ET-4632 only include properties if requested

---

web-api/openapi/CHANGELOG.md
web-api/openapi/back_office.yaml
web-api/openapi/schemas/document.yml
web-api/openapi/schemas/id.yml
web-api/openapi/schemas/time.yml
web-api/src/models.rs

**Reference**
- [ET-4670]
**Summary**
- limit snippet and string properties to max 2KB each
- clarify that string length constraints are in bytes and not characters: we've been treating the limit as bytes all the time but the openapi spec actually treats it as characters because it derives it's string definition from json. a character can be anything from one to four bytes though, which makes it impractical to use. unfortunately i haven't found a way to express this in openapi on the type level.
[ET-4670]: https://xainag.atlassian.net/browse/ET-4670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ET-4670 limit snippet and property strings to max 2KB

---

summarizer/src/lib.rs

If there isn't enough information, the summarizer returns an empty string, and we create an embedding for that.
If we can't summarize we return the original text.

Return original text if summarization fails

---

integration-tests/src/lib.rs
web-api-shared/src/elastic.rs
web-api/src/ingestion.rs
web-api/src/ingestion/routes.rs
web-api/src/storage.rs
web-api/src/storage/elastic.rs
web-api/src/storage/postgres.rs
web-api/tests/cmd/cli_overrides.auto.toml
web-api/tests/cmd/default_ingestion_config.auto.toml
web-api/tests/cmd/env_overrides.toml
web-api/tests/cmd/inline_config.auto.toml
web-api/tests/cmd/load_config.auto.toml
web-api/tests/cmd/mixed_overrides.toml
web-api/tests/manage_indexed_properties.rs

- propagate schema updates as property mapping updates to elasticsearch
- run a background job to update the indices
- [ET-4641]
[ET-4641]: https://xainag.atlassian.net/browse/ET-4641?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ET-4641 propagate schema changes to es mapping

---

web-api-db-ctrl/elasticsearch/mapping.json
web-api-db-ctrl/src/elastic.rs
web-api/src/storage/elastic.rs
web-api/tests/manage_indexed_properties.rs

If an document was ingested before a indexed property was configured it can contain a property which isn't compatible with the schema.
If that document is already an candidate and in turn uploaded to ES for various reasons we ignore such malformed documents (once we return a task with the status of the index update we can report how many documents failed, but not which).
But if that document isn't yet a candidate (or was made not a candidate and then a candidate again) we can no longer just push all it's properties to elasticsearch as this would lead to an internal server error.
There are two different solutions:
1. We filter properties when using add/set candidate.  This solution is more complicated to implement has more runtime overhead but only fixes that specific problem and touches …

ET-4719 handle property validation for making candidates

---

.github/scripts/build_ci_image.sh
.github/scripts/copyright.sh
.github/scripts/download_assets.sh
.github/scripts/wait_for_it.sh

Use `env` to execute bash to better support systems where bash is not in `/bin` (like my nixos).
We are already doing this in the justfile.
`wait_for_it.sh` is not used anywhere so is removed. Was probably used in the compose file or docker image.

Use env to execute bash

---

web-api/src/logging.rs

Flattens the fields in the root to ease access and improve readability.
The current span is already present in `spans`.

Use json to print logs

---

.spectral.js
integration-tests/src/lib.rs
web-api/openapi/CHANGELOG.md
web-api/openapi/back_office.yaml
web-api/openapi/front_office.yaml
web-api/src/mind/config.rs
web-api/src/models.rs
web-api/src/personalization.rs
web-api/src/personalization/filter.rs
web-api/src/personalization/knn.rs
web-api/src/personalization/routes.rs
web-api/src/storage.rs
web-api/src/storage/elastic.rs
web-api/src/storage/elastic/filter.rs
web-api/src/storage/memory.rs
web-api/tests/filter.rs

**Reference**
- [ET-4598]
- followed by #1003
**Summary**
- declare string filters in the spec & update changelog
- impl compare filter serde & add them in personalization routes
- add compare filter in elasticsearch calls
[ET-4598]: https://xainag.atlassian.net/browse/ET-4598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ET-4598 string filter

---

.spectral.js
web-api/openapi/CHANGELOG.md
web-api/openapi/front_office.yaml
web-api/openapi/schemas/document.yml
web-api/src/error/common.rs
web-api/src/models.rs
web-api/src/personalization/filter.rs
web-api/src/storage/elastic/filter.rs
web-api/tests/filter.rs

**Reference**
- [ET-4599]
- requires #1002
- followed by #1010
**Summary**
- declare array of strings filters in the spec & update changelog
- add containment operator to the compare filter serde
- update compare filter in elasticsearch calls
[ET-4599]: https://xainag.atlassian.net/browse/ET-4599?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ET-4599 array of strings filter

---

.spectral.js
web-api/openapi/CHANGELOG.md
web-api/openapi/front_office.yaml
web-api/src/personalization/filter.rs
web-api/src/storage/elastic/filter.rs
web-api/tests/filter.rs

**Reference**
- [ET-4605]
- requires #1003
- followed by #1016
**Summary**
- declare and/or filters in the spec & update changelog
- impl combine filter serde
- add combine filter in elasticsearch calls
[ET-4605]: https://xainag.atlassian.net/browse/ET-4605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ET-4605 and or filter

---

web-api-db-ctrl/postgres/tenant/20230628131800_document.sql
web-api/src/ingestion/routes.rs
web-api/src/mind/state.rs
web-api/src/models.rs
web-api/src/storage/memory.rs
web-api/src/storage/postgres.rs

**Open Questions:**
- ~always recompute embedding because the summerizer option might have changed~
- ~this is the most reliable solution but also means next (after update) ingestion of customers using the set candidate API will be potentially noticeable more expensive~
- ~never recompute the embedding assuming the summerizer option didn't change`~
-  the solution is that because we stored summaries earlier all documents which where summarized or have a changed snippet will be detected as having a changed snippet, in turn all documents which have the same snippet have not been summarized and only need to recalculate embedding if the state of weather or not they should be summarized changes
- issue: [ET-4674]
[ET-4674]: …

ET-4674 save original snippet instead of summary

---

web-api-db-ctrl/src/elastic.rs

- this is  already the current behavior, :pushpin: we need to handle this better for multi tenant
- issue: [ET-4689]
[ET-4689]: https://xainag.atlassian.net/browse/ET-4689?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ET-4689-check-es-index-on-startup

---

web-api/openapi/back_office.yaml
web-api/openapi/front_office.yaml
web-api/openapi/parameters/path/document_id.yml
web-api/openapi/parameters/path/id.yml
web-api/openapi/parameters/path/user_id.yml
web-api/openapi/responses/generic.yml
web-api/openapi/schemas/document.yml
web-api/openapi/schemas/error.yml
web-api/openapi/schemas/id.yml
web-api/openapi/schemas/time.yml
web-api/openapi/schemas/user.yml

**Reference**
- [ET-4772]
**Summary**
it is probably best to visually review these changes via the `just generate-openapi-doc` command:
- group routes into sections
- improve phrasing and layout
[ET-4772]: https://xainag.atlassian.net/browse/ET-4772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ET-4772 improve generated docs

---

web-api/src/error/common.rs
web-api/src/ingestion.rs
web-api/src/ingestion/routes.rs
web-api/src/mind/state.rs
web-api/src/models.rs
web-api/src/storage/memory.rs
web-api/tests/cmd/cli_overrides.auto.toml
web-api/tests/cmd/default_ingestion_config.auto.toml
web-api/tests/cmd/env_overrides.toml
web-api/tests/cmd/inline_config.auto.toml
web-api/tests/cmd/load_config.auto.toml
web-api/tests/cmd/mixed_overrides.toml
web-api/tests/ingestion.rs

**Reference**
- [ET-4812]
- #1024
**Summary**
- add max sizes for snippets and properties to ingestion conflict
- use these configs during ingestion validation
[ET-4812]: https://xainag.atlassian.net/browse/ET-4812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ET-4812 configurable snippet & properties limits

---

web-api/src/storage/elastic/filter.rs

**Reference**
- [ET-4790]
- followed by #1023
**Summary**
- add types for es clauses and impl their serialization
- convert filters to clauses and run their serialization to avoid json object handling
- remove json object handling dead code
[ET-4790]: https://xainag.atlassian.net/browse/ET-4790?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ET-4790 improve es filter serialization

---

Cargo.lock
Cargo.toml
web-api-db-ctrl/src/elastic.rs
web-api-shared/Cargo.toml
web-api-shared/src/elastic.rs
web-api-shared/src/lib.rs
web-api-shared/src/net.rs
web-api-shared/src/serde.rs
web-api/src/personalization/routes.rs
web-api/src/storage/elastic.rs
web-api/src/storage/postgres.rs
web-api/tests/cmd/cli_overrides.auto.toml
web-api/tests/cmd/default_ingestion_config.auto.toml
web-api/tests/cmd/default_personalization_config.auto.toml
web-api/tests/cmd/env_overrides.toml
web-api/tests/cmd/inline_config.auto.toml
web-api/tests/cmd/load_config.auto.toml
web-api/tests/cmd/mixed_overrides.toml

Add a retry police which is used when requests to elasticsearch fail due to network errors.
- issue: [ET-4504]
[ET-4504]: https://xainag.atlassian.net/browse/ET-4504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ET-4504 retry es once for network error

---

web-api/src/personalization/routes.rs
web-api/src/storage.rs
web-api/src/storage/elastic.rs
web-api/tests/semantic_search.rs

- use `serde(default)` to allow omitting optional fields
- add functionality to weight rrf 
- add some additional tests
With this following (undocumented , unstable) option can be passed to semantic search:
```json
{
...
"enable_hybrid_search": true,
"_dev": { "hybrid": { "customize": {
"normalize_knn": "identity",
"normalize_bm25": "identity",
"merge_fn": { "rrf": {
"knn_weight": 0.8,
"bm25_weight": 0.2
} }
} } }
}
```
This would to a hybrid search using rrf and also weight/boost the knn search by 0.8 and the bm25 search by 0.2.

dev customize hybrid option improvements

---

web-api/src/personalization.rs
web-api/src/personalization/knn.rs
web-api/src/personalization/routes.rs
web-api/tests/cmd/default_personalization_config.auto.toml
web-api/tests/semantic_search.rs

**Reference**
- [ET-4838]
**Summary**
- make the number of aKNN candidates configurable
- use this in the personalized documents search and semantic search instead of the document count
- add this to the dev options which overwrites the config if given
[ET-4838]: https://xainag.atlassian.net/browse/ET-4838?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ET-4838 configurable num candidates

---

integration-tests/src/lib.rs
web-api/openapi/CHANGELOG.md
web-api/openapi/back_office.yaml
web-api/openapi/front_office.yaml
web-api/src/ingestion/routes.rs
web-api/src/personalization/routes.rs
web-api/tests/document_candidates.rs
web-api/tests/document_properties.rs
web-api/tests/filter.rs
web-api/tests/health.rs
web-api/tests/ingestion.rs
web-api/tests/legacy_tenant_migration.rs
web-api/tests/manage_indexed_properties.rs
web-api/tests/personalized_documents.rs
web-api/tests/personalized_semantic_search.rs
web-api/tests/semantic_search.rs
web-api/tests/silo_management_api.rs
web-api/tests/store_user_history.rs
web-api/tests/tenant_id_header.rs

**Reference**
- [ET-4828]
**Summary**
- deprecate `GET /users/{id}/personalized_documents` with params in favor of `POST` with body
- add missing deprecation tests for document candidates
[ET-4828]: https://xainag.atlassian.net/browse/ET-4828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ET-4828 post personalized documents

---

web-api/openapi/CHANGELOG.md
web-api/openapi/back_office.yaml
web-api/openapi/front_office.yaml
web-api/openapi/schemas/document.yml
web-api/src/error/common.rs
web-api/src/models.rs
web-api/src/personalization/routes.rs
web-api/src/storage.rs
web-api/src/storage/elastic.rs
web-api/tests/semantic_search.rs

**Reference**
- [ET-4827]
**Summary**
- impl `DocumentQuery` wrapper and use it instead of bare strings in semantic search queries
- validate the document query in the semantic search endpoint according to the spec
[ET-4827]: https://xainag.atlassian.net/browse/ET-4827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ET-4827 validate semantic search query

---

web-api/openapi/CHANGELOG.md
web-api/openapi/front_office.yaml
web-api/src/personalization/filter.rs
web-api/src/storage/elastic/filter.rs
web-api/tests/filter.rs

**Reference**
- [ET-4792]
- requires #1023
- followed by #1027
**Summary**
- add number compare serde to routes
- update spec & tests
[ET-4792]: https://xainag.atlassian.net/browse/ET-4792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ET-4792 number filter

---

web-api/src/models.rs
web-api/src/personalization/filter.rs
web-api/src/storage/elastic/filter.rs

**Reference**
- [ET-4777]
- requires #1027
- followed by #1029
**Summary**
- logically merge elasticsearch ranges for the same property in `$and` and `$or` filters: merge `$gt` and `$gte` into a greater range as well as `$lt` and `$lte` into a less range
- for `$and` filters additionally merge the greater and less ranges into one range
[ET-4777]: https://xainag.atlassian.net/browse/ET-4777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ET-4777 merge range filter

---

web-api/src/personalization/routes.rs
web-api/src/tenants.rs
web-api/tests/cmd/cli_overrides.auto.toml
web-api/tests/cmd/default_ingestion_config.auto.toml
web-api/tests/cmd/default_personalization_config.auto.toml
web-api/tests/cmd/env_overrides.toml
web-api/tests/cmd/inline_config.auto.toml
web-api/tests/cmd/load_config.auto.toml
web-api/tests/cmd/mixed_overrides.toml
web-api/tests/semantic_search.rs

**Summary**
- deny dev access for tenants by default
- avoid false positve internal error for hybrid es rrf dev option

limit dev access for tenants

---

bert/benches/bert.rs
bert/examples/bert.rs
bert/src/config.rs
bert/src/lib.rs
bert/src/model.rs
bert/src/pipeline.rs
bert/src/tokenizer.rs

**Reference**
- [ET-4855]
**Summary**
- remove unused functions and generics related to the tokenizer in the `bert` crate
[ET-4855]: https://xainag.atlassian.net/browse/ET-4855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ET-4855 cleanup tokenizer dead code

---

Cargo.lock
bert/Cargo.toml
bert/src/config.rs
bert/src/model.rs
bert/src/tokenizer.rs
coi/src/config.rs
test-utils/src/asset.rs
web-api/src/app/state.rs
web-api/src/embedding.rs
web-api/src/ingestion.rs
web-api/src/personalization.rs
web-api/src/storage/elastic.rs
web-api/src/utils.rs

**Reference**
- [ET-4845]
**Summary**
- impl validation for front/back office configs where invariants must hold
- run validation during service startup
[ET-4845]: https://xainag.atlassian.net/browse/ET-4845?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ET-4845 validate config invariants

---

web-api/src/error/common.rs
web-api/src/personalization/routes.rs
web-api/src/storage.rs
web-api/src/storage/elastic.rs
web-api/tests/semantic_search.rs

**Reference**
- [ET-4859]
**Summary**
- remove the unavailable `DevHybrid::EsRrf` dev option and related dead code
[ET-4859]: https://xainag.atlassian.net/browse/ET-4859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ET-4859 remove unavailable es rrf dev option

---

web-api/src/error/common.rs
web-api/src/ingestion/routes.rs
web-api/src/models.rs
web-api/src/personalization/filter.rs
web-api/src/storage/property_filter.rs
web-api/tests/ingestion.rs
web-api/tests/manage_indexed_properties.rs

- report per-document errors for ingestion
- update errors to be more informative/less confusing
- be more explicit about what failed (e.g. syntax vs. length limits)
- be more explicit about where it failed (e.g. which property)
- make some errors more clear (e.g. `InvalidDocumentProperties`)
- be clear about what is expected (wrt. the failure)
- same uniform error for all "string" validation types
- do nolonger contain the malformed value (both returned and logged)
- because the malformed value could e.g. be a 2MiB DocumentId with null bytes and ascii controll codes, nothing we ever want to log
- through for this point I need some feedback, maybe we should still include it in some normalized and cut/shortened form :thinking:  
- issue: [ET-4799]
[ET-4799]: …

ET-4799 length limit and error reporting in ingestion

---

docs/source/getting_started/getting_started.md

Fix bash syntax and some json syntax.
Use variables instead of placeholders, now a curl command can be copy/pasted and it will work.
Uniform options and json style. Each invocation specifies the method.
Always use `include_properties=true`. At the moment this is the default value but we want to move it to false so it is important to  try the user always use it.
Use consisted id style `u*` for users and `xayn_*` for documents.

Uniform curl

---

web-api/src/ingestion.rs
web-api/src/ingestion/routes.rs
web-api/src/models.rs
web-api/src/personalization/filter.rs
web-api/tests/cmd/cli_overrides.auto.toml
web-api/tests/cmd/default_ingestion_config.auto.toml
web-api/tests/cmd/env_overrides.toml
web-api/tests/cmd/inline_config.auto.toml
web-api/tests/cmd/load_config.auto.toml
web-api/tests/cmd/mixed_overrides.toml

Allow to configure the maximum size of a string property.
This will need some refactoring to group all these options together and remove all the remaining hardcoded values.

Make maximum size of a string property configurable

---

web-api/openapi/CHANGELOG.md
web-api/openapi/back_office.yaml
web-api/openapi/front_office.yaml
web-api/src/personalization/routes.rs
web-api/src/storage/elastic.rs
web-api/tests/personalized_documents.rs
web-api/tests/personalized_semantic_search.rs
web-api/tests/semantic_search.rs

**Reference**
- [ET-4883]
- followed by #1047
**Summary**
- rescale es knn scores back to similarity scores
- use `ScoreMap` type alias consistently
- normalize es knn scores in cases where we use reranking with interest & tag scores, until we change how we combine the three scores we need to normalize them again
- update docs for scores
[ET-4883]: https://xainag.atlassian.net/browse/ET-4883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ET-4883 rescale es knn score

---

coi/src/config.rs
integration-tests/src/lib.rs
web-api-db-ctrl/src/lib.rs
web-api-shared/src/elastic.rs
web-api-shared/src/net.rs
web-api-shared/src/postgres.rs
web-api/src/embedding.rs
web-api/src/ingestion.rs
web-api/src/ingestion/routes.rs
web-api/src/logging.rs
web-api/src/mind/config.rs
web-api/src/mind/data.rs
web-api/src/net.rs
web-api/src/personalization.rs
web-api/src/personalization/routes.rs
web-api/src/personalization/stateless.rs
web-api/src/storage.rs
web-api/src/storage/elastic.rs
web-api/src/storage/memory.rs
web-api/src/storage/property_filter.rs
web-api/src/tenants.rs
web-api/tests/config.rs
web-api/tests/semantic_search.rs

**Summary**
- add `#[serde(deny_unknown_fields)]` to user-facing deserialized inputs like configs and requests, this helps to detect for example outdated tests, request typos, etc
- fix two outdated integration tests

deny unknown config values

---

integration-tests/src/lib.rs
web-api/src/mind/state.rs
web-api/src/models.rs
web-api/src/personalization/knn.rs
web-api/src/personalization/rerank.rs
web-api/src/personalization/routes.rs
web-api/src/storage.rs
web-api/src/storage/memory.rs
web-api/src/storage/postgres.rs
web-api/tests/semantic_search.rs

Needed for testing, previously we had dev.include_splits.
This implements most of [ET-4678] but is not quite the same, mainly it's a dev options so it doesn't yet need to lock itself into a specific format. For [ET-4678] we also need to consider the difference between raw document splits and snippets and maybe we want to compact `include_FIELD` into something like `include: Includes(HashSet<OptionalField>)` or similar.
- issue: [ET-4756]
- related: [ET-4678]
[ET-4678]: https://xainag.atlassian.net/browse/ET-4678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ET-4678]: https://xainag.atlassian.net/browse/ET-4678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

ET-4918 dev.include_snippet [1/n]

---

Cargo.lock
coi/src/document.rs
web-api-shared/Cargo.toml
web-api-shared/src/elastic.rs
web-api/src/error/common.rs
web-api/src/mind.rs
web-api/src/mind/state.rs
web-api/src/models.rs
web-api/src/personalization/knn.rs
web-api/src/personalization/rerank.rs
web-api/src/personalization/routes.rs
web-api/src/storage.rs
web-api/src/storage/elastic.rs
web-api/src/storage/elastic/filter.rs
web-api/src/storage/memory.rs
web-api/src/storage/postgres.rs
web-api/tests/elastic.rs

SnippetId is a ID into a document consisting of a document if and a snippet idx.
Added `SnippetId` into the interface and internal APIs:
- `PersonalizedDocument` now have `SnippetId` as id, when returning it we return the old `id: DocumentId` field and a `snippet_id: SnippetId` field, we will deprecate the `id` field and long term add an option to not include it for new tenants
- `/semantic_search` new accepts both a  `SnippetId` and `DocumentId`
- internal APIs use `SnippetId` where appropriate
- except for mind related code which for now keeps using `DocumentId` where possible, we can add better snippet id support for it later
- doesn't yet change any internal representation, DB code etc.
- there is one small exception around excluded documents &  elastic search filters  …

ET-4921  SnippetId in interface [4/n]

---

Cargo.lock
web-api-db-ctrl/elasticsearch/mapping.json
web-api-db-ctrl/postgres/tenant/20230713173212_document.sql
web-api-db-ctrl/postgres/tenant/20230807103000_interaction.sql
web-api/Cargo.toml
web-api/src/ingestion/preprocess.rs
web-api/src/ingestion/routes.rs
web-api/src/mind/state.rs
web-api/src/models.rs
web-api/src/personalization/routes.rs
web-api/src/personalization/stateless.rs
web-api/src/storage.rs
web-api/src/storage/elastic.rs
web-api/src/storage/memory.rs
web-api/src/storage/postgres.rs
web-api/src/storage/utils.rs

Add support for multi-snippet documents in postgres (and only there).
- support for interacting with multi-snippet document is still only semi-supported as there are a bunch of open questions currently it will convert all "interacted with document id" occurrences with "interacted with first snippet of document" but also for search exclusions "exclude all documents with any interaction" 
- memory/mind db are still assuming single snippet documents, changing this would require rewriting huge portions of the memory impl.
- issue: [ET-4756]
- based on #1055 
[ET-4756]: …

ET-4923 multi split support in postgres [6/n]

---

Cargo.lock
web-api-db-ctrl/postgres/tenant/20230807104500_document.sql
web-api/Cargo.toml
web-api/src/error/common.rs
web-api/src/ingestion/preprocess.rs
web-api/src/ingestion/routes.rs
web-api/src/models.rs
web-api/tests/ingestion.rs
web-api/tests/split_documents.rs

- add support for preprecessing documents using cutters
- readded tests for split documents
- issue: [ET-4756]
- based on #1057 
[ET-4756]: https://xainag.atlassian.net/browse/ET-4756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ET-4925 support document splitting using cutters [8/n]

---

web-api/src/app/state.rs
web-api/src/embedding.rs
web-api/src/ingestion/preprocess.rs
web-api/src/ingestion/routes.rs
web-api/src/mind.rs
web-api/src/mind/state.rs
web-api/src/models.rs
web-api/src/personalization/routes.rs

Summary:
- makes the embedder `run` and `load` function async
- required for sagemaker integration (see #1043)

ET-4937 make embedder async

---

.github/actions/release_artifact/action.yml
.github/scripts/download_assets.sh
.github/workflows/web-service.yml
Cargo.lock
Cargo.toml
bert/Cargo.toml
bert/benches/bert.rs
bert/src/config.rs
bert/src/lib.rs
bert/src/model.rs
bert/src/pipeline.rs
bert/src/pooler.rs
integration-tests/src/lib.rs
justfile
test-utils/Cargo.toml
test-utils/src/asset.rs
web-api/compose.db.yml
web-api/src/embedding.rs
web-api/src/utils.rs
web-api/tests/cmd/assets/config.toml
web-api/tests/cmd/cli_overrides.auto.toml
web-api/tests/cmd/default_ingestion_config.auto.toml
web-api/tests/cmd/default_personalization_config.auto.toml
web-api/tests/cmd/env_overrides.toml
web-api/tests/cmd/inline_config.auto.toml
web-api/tests/cmd/load_config.auto.toml
web-api/tests/cmd/mixed_overrides.toml
web-api/tests/config.rs
web-api/tests/legacy_tenant_migration.rs

**Reference**
- [ET-4300]
- [ET-4912]
- [ET-4301]
- followed by #1066
**Summary**
Initial support for ort to compute the embeddings.
It can be selected with an option.
Some data structure it is converted to the tract one to avoid changing too much.
To deploy it, some changes can be needed in a follow-up.
Once we have ort working and deployed, we can remove tract.
- currently the onnxruntime lib is added to the assets bucket, probably will be added to the ci image later (but no gpu lib yet)
- integration tests already run with onnxruntime instead of tract
- engine defaults run with onnxruntime
- webservice build also copies onnxruntime files
- update the benchmark, the results are in [ET-4301]
- image builds successfully: https://github.com/xaynetwork/xayn_discovery_engine/actions/runs/5857 …

ET-4300 Add ort

---

Cargo.lock
Cargo.toml
bert/Cargo.toml
bert/benches/bert.rs
bert/examples/bert.rs
bert/src/config.rs
bert/src/lib.rs
bert/src/model.rs
bert/src/pipeline.rs
bert/src/pooler.rs
bert/src/tokenizer.rs
web-api/src/embedding.rs
web-api/src/mind/state.rs
web-api/tests/cmd/cli_overrides.auto.toml
web-api/tests/cmd/default_ingestion_config.auto.toml
web-api/tests/cmd/default_personalization_config.auto.toml
web-api/tests/cmd/env_overrides.toml
web-api/tests/cmd/inline_config.auto.toml
web-api/tests/cmd/load_config.auto.toml
web-api/tests/cmd/mixed_overrides.toml

**Reference**
- [ET-4943]
- requires #1054
- followed by #1067
**Summary**
- remove `tract` dependency
- use `ort` native types for model inputs and outputs
[ET-4943]: https://xainag.atlassian.net/browse/ET-4943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ET-4943 remove tract

---

.github/scripts/download_assets.sh
.github/workflows/web-service.yml
bert/src/config.rs
bert/src/model.rs
bert/src/pipeline.rs
bert/src/tokenizer.rs
integration-tests/src/lib.rs
justfile
onnx-tool/README.md
onnx-tool/requirements.txt
onnx-tool/src/mock_onnx_tool.py
test-utils/src/asset.rs
web-api/tests/legacy_tenant_migration.rs

**Reference**
- [ET-4949]
- requires #1066
**Summary**
- remove fixed token size:
- padding is set to longest of the batch, currently that means no padding at all, if we chose to go with batch sizes > 1 then this will actually take effect
- truncation is still applied, the token size keeps its meaning in that regard that it acts as a max token size, this also means that the embedding computation is not breaking for existing tenants (removed padding is also not breaking because we average-pool the embeddings only over the active tokens which doesn't apply to padding tokens)
- removed unused model config values & simplify/consistify remaining config values, all used models have been updated accordingly:
- `smbert`: `v0004` -> `v0005`
- `smbert_mocked`: `v0004` -> `v0005`
- `e5_mocked`: …

ET-4949 dynamic token size

---

web-api-db-ctrl/postgres/tenant/20230713173212_document.sql

This only works if the migration (and any follow up migrations) haven't been applied already due to it changing an existing migration. Outside of one demo tenant that seems to be the case.
Run `cargo clean -p xayn-web-api-db-ctrl` can be a good idea to preclude any cargo cache related issues.

change migration to not calculate hash

---

web-api/openapi/front_office.yaml
web-api/openapi/schemas/document.yml
web-api/src/personalization/routes.rs
web-api/tests/semantic_search.rs
web-api/tests/split_documents.rs

Turns the `_dev.include_snippet` option into a non-dev and documented option.
Also adds it to all endpoints which have `include_properties` and didn't yet had a `_dev.include_snippet` option.
- issue: [ET-4678]
[ET-4678]: https://xainag.atlassian.net/browse/ET-4678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ET-4678 allow returning snippet

---

web-api/src/storage/postgres.rs

filter get_personalized by "WHERE is_candidate"
this means that even if we fail to delete documents in elastic search (or there is some race condition) we filter out documents which are no longer candidates when enriching search hits with additional data  
this doesn't fully fix the bug, but reduces the negative consequences of it

ET-4957 quick fix for es deletion bug

---

.github/workflows/_reusable.rust.yml
Cargo.lock
integration-tests/src/lib.rs
web-api/Cargo.toml
web-api/compose.db.yml
web-api/openapi/back_office.yaml
web-api/openapi/front_office.yaml
web-api/src/app.rs
web-api/src/app/state.rs
web-api/src/error/common.rs
web-api/src/extractor.rs
web-api/src/ingestion.rs
web-api/src/ingestion/preprocessor.rs
web-api/src/ingestion/routes.rs
web-api/src/lib.rs
web-api/src/personalization.rs
web-api/tests/cmd/cli_overrides.auto.toml
web-api/tests/cmd/default_ingestion_config.auto.toml
web-api/tests/cmd/default_personalization_config.auto.toml
web-api/tests/cmd/env_overrides.toml
web-api/tests/cmd/inline_config.auto.toml
web-api/tests/cmd/load_config.auto.toml
web-api/tests/cmd/mixed_overrides.toml
web-api/tests/ingestion.rs

Allow to upload a binary. We pass the binary through tika to extract the text.
By default, this is disabled at the system level. If used when disabled, an error that says that it is disabled is returned.
The text extractor configuration already provides a way to specify which extractor we are using to make it future-proof. At the moment, we don´t plan to use something else but it will make it easier to switch to something else. 
Some changes involve allowing the preprocess to return a bad request kind of error.
Also with updated spec.

Upload file

---

web-api/src/error/common.rs
web-api/src/extractor.rs
web-api/src/ingestion/preprocessor.rs
web-api/src/ingestion/routes.rs
web-api/src/models.rs
web-api/src/personalization.rs
web-api/src/personalization/routes.rs
web-api/src/storage/memory.rs
web-api/tests/cmd/default_personalization_config.auto.toml
web-api/tests/ingestion.rs

- updated `string_wrapper!` to allow not having a hard coded len bound 
- now we can use it again for `DocumentSnippet`, so we do so
- then change `DocumentQuery` to not use a hard coded bound
- issue: [ET-4999]
[ET-4999]: https://xainag.atlassian.net/browse/ET-4999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ET-4999 make search query size configurable

---

.github/workflows/web-service.yml

the docker job often takes longer than 10 min. This pr increases the timeout to 20min 
- https://github.com/xaynetwork/xayn_discovery_engine/actions/runs/6239554682/job/16938040018
- https://github.com/xaynetwork/xayn_discovery_engine/actions/runs/6246363316/attempts/1
- https://github.com/xaynetwork/xayn_discovery_engine/actions/runs/6238156583/attempts/1
- https://github.com/xaynetwork/xayn_discovery_engine/actions/runs/6238156583/attempts/2

ET-5027 increase timeout to 20 min

---

docs/source/getting_started/getting_started.md
docs/source/index.rst

[RST uses asterisks to show text as italic](https://sublime-and-sphinx-guide.readthedocs.io/en/latest/inline.html#italic-text)

fix typo and formatting

---

docs/source/getting_started/getting_started.md
web-api/openapi/CHANGELOG.md
web-api/openapi/back_office.yaml
web-api/openapi/front_office.yaml
web-api/src/personalization/routes.rs
web-api/tests/et_4957_es_deletion.rs
web-api/tests/recommendations.rs
web-api/tests/split_documents.rs
web-api/tests/store_user_history.rs

Fully rename personalized_documents to recommendations in documentation (rust code still uses `PersonalizedDocuments` ans similar  in some cases internally).
This now clearly separates the feature of finding recommendation and personalizing search. It also avoids issues like `PersonalizedDocument` not being a personalized document as we do not personalize the document. It's just part of a group of documents which order/choice of inclusion has been personalized. (It's also strictly speaking not a document but a snippet id and the scoring of the search for that snippet and optionally the properties of the document the snippet is from).
`/users/{user_id}/personalized_documents` => `/users/{user_id}/recommendations`

ET-5059 rename personalize to recommendations

---

web-api/src/models.rs
web-api/src/personalization/knn.rs
web-api/src/personalization/rerank.rs
web-api/src/personalization/routes.rs
web-api/src/storage.rs
web-api/src/storage/elastic.rs
web-api/src/storage/memory.rs
web-api/src/storage/postgres.rs
web-api/tests/semantic_search.rs

Show raw scores from Elastic if a dev option is passed.
Passing the dev option is at the moment missing.

Bubbling raw scores from elastic up to the response

---

justfile

This allows to set the AWS_PROFILE env variable from outside and from the .env file or from the `.vscode/settings.json` in vscode:
```json
{
"terminal.integrated.env.osx": {
"AWS_PROFILE" : "YourAlternativeProfile"
}
}
```

Allow AWS_PROFILE to be set from outside

---

bert/src/model.rs

During the drop of `Session` the `Environment` is dropped before the session, this causes the random block of the test.
This has been fixed upstream https://github.com/pykeio/ort/pull/105 but it has not been ported to the `1.16` branch nor it has been released yet.

Fix stuck tests

---

justfile
web-api/compose.ingestion.yml
web-api/compose.personalization.yml

In #1072 the service name `db_ready` has been renamed to `services_ready`. This pr fixes the references to the old service name.

Fix service name in docker compose

---

web-api/src/embedding.rs
web-api/src/ingestion.rs
web-api/src/ingestion/preprocessor.rs
web-api/src/ingestion/routes.rs
web-api/src/mind/state.rs
web-api/src/personalization/routes.rs
web-api/tests/cmd/cli_overrides.auto.toml
web-api/tests/cmd/default_ingestion_config.auto.toml
web-api/tests/cmd/default_personalization_config.auto.toml
web-api/tests/cmd/env_overrides.toml
web-api/tests/cmd/inline_config.auto.toml
web-api/tests/cmd/load_config.auto.toml
web-api/tests/cmd/mixed_overrides.toml

Allows specifying two prefixes:
- `embedding.prefix.query` prefix all queries with this before computing their embedding
- `embedding.prefix.snippet` prefix all snippets with this before computing their embedding
works for both local and sagemaker setups
Env variables:
- `XAYN_WEB_API__EMBEDDING__PREFIX__QUERY`
- `XAYN_WEB_API__EMBEDDING__PREFIX__SNIPPET`

ET-4885 allow to prefix snippets

---

.spectral.js
web-api/openapi/front_office.yaml
web-api/src/personalization/filter.rs
web-api/src/storage/elastic/filter.rs

Support filtering by document ids.
For now limit proper support to use cases which do not use document splitting (we can add that later if it's needed).
- [ET-4780]
[ET-4780]: https://xainag.atlassian.net/browse/ET-4780?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ET-4780 support document id filters

---

Cargo.lock
web-api/Cargo.toml
web-api/src/embedding.rs

Add support to use OpenAi embedding models. This allows us to use openai and azure services.
This also fixes the prefix for sagemaker.

Add support for openai

---

docs/source/getting_started/getting_started.md

We cannot use single quote in the text because we use it to delimit the json data.

Fix example in doc

---

Cargo.lock
integration-tests/Cargo.toml
integration-tests/tests/legacy_tenant_migration.rs

All the deployments we have are after the migration point we are checking here so this test is useless.
Pointing to our version in the past increases the compilation time for the tests by 30s and brings in a lot of older dependencies.
This also creates a problem with cargo-chef that cannot handle a dependency with different versions (see next PR).

Remove obsolete migration test

---

web-api-shared/src/elastic.rs
web-api/src/storage/elastic.rs

- ignore version conflict of `delete_by_parent`
- but still warn if it happens
- change `freshly_insert_document` to use `index` instead of `create`, so it will replace existing documents with the
same ID,  while `freshly_insert_document` is supposed to only be called with snippet ids not in elastic search there seems to be a race condition where this isn't the case, maybe related to `delete_by_parent`
- but still warn if it happens

ET-5451 reduce probability of delete->insert race conditions
