- discovery_engine/example/lib/example.dart
- discovery_engine/lib/src/domain/models/feed_market.dart
- discovery_engine/test/discovery_engine/change_configuration_test.dart
- discovery_engine/test/discovery_engine/utils/utils.dart
- discovery_engine_flutter/example/lib/main.dart
Rename variable `countyCode` -> `countryCode` 😅
> Rename variable `countyCode` -> `countryCode`

- discovery_engine/lib/src/domain/document_manager.dart
- discovery_engine/lib/src/domain/engine/engine.dart
- discovery_engine/lib/src/domain/engine/mock_engine.dart
- discovery_engine/lib/src/domain/feed_manager.dart
**Summary**
adds a `FeedManager` class, with handlers for the feed events:
- _feed documents closed_
- _next feed batch requested_
(_feed requested_ event will be handled in the next pr)
> TY-2142 feed manager: feedDocumentsClosed, nextFeedBatchRequested

- discovery_engine/lib/src/api/api.dart
- discovery_engine/lib/src/api/events/client_events.dart
- discovery_engine/lib/src/discovery_engine_base.dart
- discovery_engine/lib/src/discovery_engine_worker.dart
- discovery_engine/lib/src/domain/document_manager.dart
- discovery_engine/test/codecs/mocks.dart
- discovery_engine/test/discovery_engine/utils/utils.dart
- discovery_engine_core/core/src/document.rs
- discovery_engine_core/core/src/engine.rs
- discovery_engine_core/core/src/stack.rs
Add to `Engine`:
* `time_logged` to learn from the time a user spent on a document,
* `user_reacted` to learn from the reaction of a user to a document,
Since both of this will trigger the feedback loop of the `Ranker` we rank the document of each `Stack` again after this.
> TY-2236 Add function to learn from user feedback

- discovery_engine/lib/src/domain/models/document.dart
- discovery_engine/lib/src/domain/models/feed_market.dart
- discovery_engine/test/discovery_engine/configuration_test.dart
- discovery_engine/test/ffi/ffi_test.dart
- discovery_engine_core/bindings/build.rs
**Summary**
adds a timestamp field to the `Document` class.
> TY-2286 add timestamp to documents

- discovery_engine/lib/src/domain/models/feed_market.dart
- discovery_engine_core/Cargo.lock
- discovery_engine_core/Cargo.toml
- discovery_engine_core/providers/Cargo.toml
- discovery_engine_core/providers/src/client.rs
- discovery_engine_core/providers/src/expression.rs
- discovery_engine_core/providers/src/filter.rs
- discovery_engine_core/providers/src/languages.rs
- discovery_engine_core/providers/src/lib.rs
- discovery_engine_core/providers/src/query.rs
It adds a mock of the `Client` struct and api.
It adds the data structure to let the user filter the documents he is interested in (`Filter`).
> TY 2276 define client api

- .github/workflows/ci.yml
- .gitignore
- discovery_engine/.gitignore
- discovery_engine_flutter/.gitignore
- discovery_engine_flutter/ios/Classes/XaynDiscoveryEngineFlutterPlugin.h
- justfile
CI will be updated in follow up PR (dedup, etc.)
> TY 2273 use job runner for local scripts

- .github/workflows/ci_reusable_wf.yml
Before using reusable workflows we need to have the workflow on the `main` branch.
> DEVOPS-671 Creating the reusable wf file

- .github/workflows/ci_reusable_wf.yml
Adding the checks for a good run inside the workflow file and deleting outputs.
> DEVOPS-671 Adding new checks inside the workflow reuse

- discovery_engine/example/lib/example.dart
- discovery_engine/lib/src/discovery_engine_base.dart
- discovery_engine/lib/src/domain/models/configuration.dart
- discovery_engine/test/discovery_engine/configuration_test.dart
- discovery_engine/test/discovery_engine/utils/utils.dart
- discovery_engine_flutter/example/lib/main.dart
- discovery_engine_flutter/example/pubspec.lock
[Jira ref](https://xainag.atlassian.net/browse/TY-2327)
Added `assetsUrl` to `Configuration` object for Discovery Engine.
> TY-2327 Added `assetsUrl` to `Configuration`

- .github/workflows/ci_reusable_wf.yml
Creating a new output on the workflow reuse for checking the output value.
> DEVOPS-671 Adding a new output wf reuse

- bors.toml
Adding a shorter timeout for the bors configuration.
> DEVOPS-931 Changing timeout for bors

- web-api-shared/src/elastic.rs
- web-api-shared/src/serde.rs
- web-api/src/personalization/knn.rs
- web-api/src/personalization/routes.rs
- web-api/src/storage.rs
- web-api/src/storage/elastic.rs
- web-api/src/storage/memory.rs
- web-api/src/storage/postgres.rs
- web-api/src/utils.rs
Refecators the ES search code to be better readable.
There are a number of TODOs where I wasn't clear if something was a bug or intended behavior.
> ET-4538 refactor ES  search code

- web-api-shared/src/elastic.rs
Could be rebased onto main, but would make already nasty merge conflicts for #967 worse.
- [ET-4572]
[ET-4572]: https://xainag.atlassian.net/browse/ET-4572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ET-4572  set track_total_hits to false

- web-api/openapi/back_office.yaml
- web-api/openapi/schemas/document.yml
- web-api/openapi/schemas/id.yml
- web-api/src/models.rs
**Reference**
- [ET-4595]
**Summary**
- update spec
- disallow dots in property ids
- disallow underscore prefix in all ids
[ET-4595]: https://xainag.atlassian.net/browse/ET-4595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ET-4595 restrict ids

- web-api/openapi/back_office.yaml
- web-api/openapi/schemas/document.yml
- web-api/src/error/common.rs
- web-api/src/ingestion/routes.rs
- web-api/src/models.rs
- web-api/src/personalization/routes.rs
- web-api/src/storage.rs
- web-api/src/storage/elastic.rs
- web-api/src/storage/postgres.rs
**Reference**
- [ET-4575]
**Summary**
- update spec with property limitations
- add property validation
[ET-4575]: https://xainag.atlassian.net/browse/ET-4575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ET-4575 validate properties

- .spectral.js
- web-api/openapi/CHANGELOG.md
- web-api/openapi/back_office.yaml
- web-api/openapi/front_office.yaml
- web-api/openapi/schemas/document.yml
- web-api/openapi/schemas/id.yml
- web-api/src/error/common.rs
- web-api/src/ingestion/routes.rs
- web-api/src/mind.rs
- web-api/src/mind/data.rs
- web-api/src/mind/state.rs
- web-api/src/models.rs
- web-api/src/personalization/knn.rs
- web-api/src/personalization/rerank.rs
- web-api/src/personalization/routes.rs
- web-api/src/personalization/stateless.rs
- web-api/src/storage.rs
- web-api/src/storage/elastic.rs
- web-api/src/storage/memory.rs
- web-api/src/storage/postgres.rs
- web-api/tests/document_candidates.rs
- web-api/tests/health.rs
- web-api/tests/personalized_documents.rs
- web-api/tests/personalized_semantic_search.rs
- web-api/tests/semantic_search.rs
**Reference**
- [ET-4593]
- [ET-4575]
- [ET-4594]
- [ET-4595]
- [ET-4629]
- [ET-4628]
- [ET-4632]
- [ET-4634]
**Summary**
- bump major spec version
- add spec changelog
- collect breaking changes:
- #984
- #982
- #985
- #986
- #987
- #989
- #990
- #991
[ET-4575]: https://xainag.atlassian.net/browse/ET-4575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ET-4593]: https://xainag.atlassian.net/browse/ET-4593?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ET-4594]: https://xainag.atlassian.net/browse/ET-4594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ET-4595]: https://xainag.atlassian.net/browse/ET-4595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2 …
> Breaking changes: spec v2

- bert/Cargo.toml
**Reference**
- [ET-4636]
- #992
**Summary**
- fix feature in `tokenizers` dependency
[ET-4636]: https://xainag.atlassian.net/browse/ET-4636?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ET-4636 fix tokenizers dep

- web-api/openapi/back_office.yaml
- web-api/openapi/front_office.yaml
- web-api/openapi/schemas/document.yml
- web-api/src/models.rs
Null is as a value in the properties and it is thread as if the property has no value.
> ET 4677 null is ok

- .spectral.js
- web-api-db-ctrl/postgres/tenant/20230621153200_indexed_properties.sql
- web-api/openapi/CHANGELOG.md
- web-api/openapi/back_office.yaml
- web-api/openapi/front_office.yaml
- web-api/openapi/schemas/document.yml
- web-api/src/error/application.rs
- web-api/src/error/common.rs
- web-api/src/ingestion.rs
- web-api/src/ingestion/routes.rs
- web-api/src/storage.rs
- web-api/src/storage/postgres.rs
- web-api/src/storage/property_filter.rs
- web-api/tests/cmd/cli_overrides.auto.toml
- web-api/tests/cmd/default_ingestion_config.auto.toml
- web-api/tests/cmd/env_overrides.toml
- web-api/tests/cmd/inline_config.auto.toml
- web-api/tests/cmd/load_config.auto.toml
- web-api/tests/cmd/mixed_overrides.toml
- get indexed property schema from postgres
- update indexed property schema in postgres
- do not yet update ES mapping, **merge #997 into this PR before merging it into main**
- does not yet contain integration test 
- story: [ET-4602]
- issue: [ET-4640]
[ET-4602]: https://xainag.atlassian.net/browse/ET-4602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ET-4640]: https://xainag.atlassian.net/browse/ET-4640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ET-4640  update/get indexed property schema from postgres

- web-api/src/error/common.rs
- web-api/src/ingestion/routes.rs
- web-api/src/models.rs
- web-api/src/storage.rs
- web-api/src/storage/property_filter.rs
- web-api/tests/manage_indexed_properties.rs
Check indexed properties to be compatible with given schema.
- story [ET-4602]
- issue [ET-4645]
[ET-4602]: https://xainag.atlassian.net/browse/ET-4602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ET-4645]: https://xainag.atlassian.net/browse/ET-4645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ET-4645 check indexed properties when ingesting

- web-api/openapi/front_office.yaml
Describe all the other ways this endpoint can be sued.
> Update semantic_search's doc

- web-api/openapi/back_office.yaml
- comment it out for now such that it doesn't become part of the generated docs
> hide docs of unreleased features

- web-api/openapi/CHANGELOG.md
- web-api/openapi/back_office.yaml
- web-api/openapi/front_office.yaml
**Reference**
- [ET-4768]
- requires #1016
**Summary**
- reenable indexed property docs
- update changelog version & date
[ET-4768]: https://xainag.atlassian.net/browse/ET-4768?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ET-4768 reenable docs of unreleased features

- web-api/openapi/front_office.yaml
- web-api/src/personalization/filter.rs
for filter `$in` 10  => 500
be aware the JSON body size limits still apply
> increase filter limits

- web-api/src/models.rs
**Reference**
- [ET-4812]
**Summary**
- quick fix prior to the aktual impl
[ET-4812]: https://xainag.atlassian.net/browse/ET-4812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PRE ET-4812 increase snippet and properties byte size limits

- Cargo.lock
- web-api/Cargo.toml
- web-api/openapi/CHANGELOG.md
- web-api/openapi/back_office.yaml
- web-api/openapi/front_office.yaml
- web-api/src/personalization/filter.rs
- web-api/src/storage/elastic/filter.rs
- web-api/tests/filter.rs
**Reference**
- [ET-4791]
- requires #1022
- followed by #1026
**Summary**
- add boolean compare serde to routes
- update spec & tests
[ET-4791]: https://xainag.atlassian.net/browse/ET-4791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ET-4791 boolean filter

- web-api/src/storage/elastic.rs
- web-api/src/storage/elastic/filter.rs
**Reference**
- [ET-4820]
- requires #1028
**Summary**
- impl `Clauses` as the root filter clauses wrapper, don't convert it into a json object inside the filter module
[ET-4820]: https://xainag.atlassian.net/browse/ET-4820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ET-4820 wrap clause type

- web-api/openapi/CHANGELOG.md
- web-api/openapi/back_office.yaml
- web-api/openapi/front_office.yaml
- web-api/src/error/common.rs
- web-api/src/ingestion/routes.rs
- web-api/src/models.rs
- web-api/src/personalization/filter.rs
- web-api/src/personalization/routes.rs
- web-api/src/storage/property_filter.rs
- web-api/tests/filter.rs
- web-api/tests/manage_indexed_properties.rs
**Reference**
- [ET-4775]
**Summary**
- impl filter validation wrt the indexed properties schema
- improve filter serde tests & add filter validation tests
[ET-4775]: https://xainag.atlassian.net/browse/ET-4775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ET-4775 check filter against property schema

- Cargo.lock
- Cargo.toml
- bert/Cargo.toml
- coi/Cargo.toml
- integration-tests/Cargo.toml
- summarizer/Cargo.toml
- web-api-db-ctrl/Cargo.toml
- web-api-shared/Cargo.toml
- web-api/Cargo.toml
**Summary**
- prune unused cargo dependencies with the help of `cargo machete`
> prune unused deps

- Cargo.lock
- Cargo.toml
- web-api-db-ctrl/Cargo.toml
- web-api-db-ctrl/postgres/tenant/20230810001355_external_migration.sql
- web-api-db-ctrl/src/elastic.rs
- web-api-db-ctrl/src/lib.rs
- web-api-db-ctrl/src/postgres.rs
- web-api-db-ctrl/src/postgres/extern_migrations.rs
- web-api-shared/src/elastic.rs
- web-api-shared/src/net.rs
- web-api/Cargo.toml
- web-api/src/storage/elastic.rs
- web-api/src/storage/elastic/filter.rs
- web-api/src/storage/postgres.rs
- web-api/tests/cmd/cli_overrides.auto.toml
- web-api/tests/cmd/default_ingestion_config.auto.toml
- web-api/tests/cmd/default_personalization_config.auto.toml
- web-api/tests/cmd/env_overrides.toml
- web-api/tests/cmd/inline_config.auto.toml
- web-api/tests/cmd/load_config.auto.toml
- web-api/tests/cmd/mixed_overrides.toml
- web-api/tests/legacy_tenant_migration.rs
Support multi-snippet documents in elastic search.
- issue: [ET-4756]
- based on #1056 
[ET-4756]: https://xainag.atlassian.net/browse/ET-4756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ET-4924 multi snippet support in es [7/n]

- web-api/openapi/back_office.yaml
- web-api/openapi/front_office.yaml
- web-api/openapi/schemas/document.yml
Updated documentation.
- issue: [Et-4895]
- based on: #1058
> ET-4895 update docs [9/n]

- web-api/src/personalization/routes.rs
- web-api/src/personalization/stateless.rs
- web-api/src/storage/postgres.rs
- web-api/tests/split_documents.rs
Update test to include ET-4886 use case.
- issue: [ET-4886]
- based on #1062 
[ET-4886]: https://xainag.atlassian.net/browse/ET-4886?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ET-4886 update test [10/n]

- .github/workflows/web-service.yml
- Cargo.lock
- web-api/Cargo.toml
- web-api/Dockerfile
- web-api/src/embedding.rs
Summary:
- add sagemaker embedder
- add the possibility to add a target model (required for multi model mode)
- add the possibility to retry a sagemaker request
> ET-4750 sagemaker

- .github/docker/Dockerfile.ci-image
- .github/workflows/CI.yml
- .github/workflows/_reusable.rust.yml
- .github/workflows/ci-image.yml
- .github/workflows/web-service.yml
- bert/src/model.rs
- web-api/src/storage/elastic/filter.rs
Include `pipenv` and nltk punkt data into CI build image.
> ET-4866-1 update build image

- web-api/tests/es_deletion_bug.rs
- web-api/tests/et_4957_es_deletion.rs
Replicate behavior which lead to some deletion bugs in test.
> ET-4957 more test

- docs/source/getting_started/getting_started.md
Update getting started documentation to reflect changes regarding split documents and documents with multiple snippets.
> ET-4971 doc for split documents

- Cargo.lock
- Cargo.toml
- integration-tests/Cargo.toml
- integration-tests/src/lib.rs
- snippet-extractor/Cargo.toml
- snippet-extractor/python_src/snippet_extractor.py
- snippet-extractor/src/lib.rs
- snippet-extractor/src/pool.rs
- snippet-extractor/tests/basic_functionality.rs
- web-api/src/error/common.rs
- web-api/src/ingestion.rs
- web-api/src/ingestion/preprocessor.rs
- web-api/src/ingestion/routes.rs
- web-api/tests/cmd/cli_overrides.auto.toml
- web-api/tests/cmd/default_ingestion_config.auto.toml
- web-api/tests/cmd/env_overrides.toml
- web-api/tests/cmd/inline_config.auto.toml
- web-api/tests/cmd/load_config.auto.toml
- web-api/tests/cmd/mixed_overrides.toml
- provide more error context for acquisition errors
- display errors in logging
- some minor refactoring 
- force initialization of all child processes on startup of the service 
- better error logging, especially in case of discarding unhealthy children
- fix health check
> improve python pool handling

- coi/src/point.rs
- web-api/src/lib.rs
- web-api/src/models.rs
- web-api/src/personalization.rs
- web-api/src/personalization/knn.rs
- web-api/src/personalization/rerank.rs
- web-api/src/personalization/routes.rs
- web-api/src/rank_merge.rs
- web-api/src/storage/elastic.rs
- web-api/src/storage/postgres.rs
- web-api/tests/cmd/default_personalization_config.auto.toml
- web-api/tests/personalized_documents.rs
- issue: [ET-4891]
[ET-4891]: https://xainag.atlassian.net/browse/ET-4891?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ET-4891 use rrf everywhere

- web-api/compose.single-machine-deploy.yml
- issue: [ET-4939](https://xainag.atlassian.net/jira/software/projects/ET/boards/51?selectedIssue=ET-4939)
[ET-4939]: https://xainag.atlassian.net/browse/ET-4939?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> add single machine deploy compose

- docs/source/getting_started/getting_started.md
> remove backticks in note

- web-api/openapi/front_office.yaml
- story [ET-4823]
- issue [ET-4995]
[ET-4823]: https://xainag.atlassian.net/browse/ET-4823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ET-4995]: https://xainag.atlassian.net/browse/ET-4995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ET-4995 missing defaults in documentation

- web-api/compose.single-machine-deploy.yml
Fix some ports.
Move back end front office to different ports.
Enable tika.
Update image
> Update single machine deploy
